apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: projecttrack-rbac
data:
  PORT: "5000"
  NODE_ENV: "production"
  CORS_ORIGIN: "*"
  MONGO_URI: "mongodb://mongo:27017/projecttrack"
  JWT_EXPIRES_IN: "15m"
  REFRESH_TOKEN_TTL_SEC: "604800"
  PASSWORD_RESET_TTL_SEC: "900"

  CLIENT_URL: "https://936f2e47695e-10-244-7-165-3000.spch.r.killercoda.com"

  SMTP_HOST: "mailhog"
  SMTP_PORT: "1025"
  SMTP_SECURE: "false"
  MAIL_FROM: "no-reply@example.com"
  DEFAULT_REGISTRATION_ROLE: "Dev"